const fs = require('fs');
const path = 'C:/BCL/BC-Learning-Main/elearning-assets/phase4-dashboard.html';
let content = fs.readFileSync(path, 'utf8');

const newFunction = [
  "async function fetchNetworkInfo() {",
  "            const infoDiv = document.getElementById('network-info');",
  "            if (!infoDiv) {",
  "                console.warn('❌ network-info element not found');",
  "                return;",
  "            }",
  "            if (networkFetchInFlight) {",
  "                console.log('⏳ Network info request already in progress');",
  "                return;",
  "            }",
  "            networkFetchInFlight = true;",
  "            infoDiv.innerHTML = '<span class=loading></span> Memuat info jaringan...';",
  "            console.log('🔍 Starting network info fetch...');",
  "",
  "            const hardTimeoutMs = 10000;",
  "            let timedOut = false;",
  "            const hardTimeoutId = setTimeout(() => {",
  "                timedOut = true;",
  "                infoDiv.innerHTML = '<span style=color:#ef4444>⏰ Timeout: Server tidak merespons</span>';",
  "                networkFetchInFlight = false;",
  "            }, hardTimeoutMs);",
  "",
  "            const endpoints = [",
  "                '/api/network-info'",
  "            ];",
  "            // Fallback to same host on port 5052 (when dashboard served on port 80/443)",
  "            if (location.hostname) {",
  "                endpoints.push(location.protocol + '//' + location.hostname + ':5052/api/network-info');",
  "            }",
  "            // Extra fallback to localhost",
  "            endpoints.push('http://localhost:5052/api/network-info');",
  "",
  "            try {",
  "                await new Promise(resolve => setTimeout(resolve, 300));",
  "                if (timedOut) {",
  "                    return;",
  "                }",
  "                let lastError = null;",
  "                for (const url of endpoints) {",
  "                    try {",
  "                        console.log('📡 Fetching from', url);",
  "                        const response = await fetch(url, {",
  "                            method: 'GET',",
  "                            headers: {",
  "                                'Accept': 'application/json'",
  "                            }",
  "                        });",
  "                        if (!response.ok) {",
  "                            throw new Error('HTTP ' + response.status + ': ' + response.statusText);",
  "                        }",
  "                        const data = await response.json();",
  "                        if (timedOut) {",
  "                            return;",
  "                        }",
  "                        console.log('📊 Data received:', data);",
  "                        let html = '<b>IP Server:</b> ' + (data.serverIPs && data.serverIPs.length ? data.serverIPs.join(', ') : '-') + '<br>';",
  "                        html += '<b>IP Anda:</b> ' + (data.userIP || '-') + '<br>';",
  "                        infoDiv.innerHTML = html;",
  "                        console.log('✅ Network info loaded successfully');",
  "                        clearTimeout(hardTimeoutId);",
  "                        networkFetchInFlight = false;",
  "                        return;",
  "                    } catch (err) {",
  "                        lastError = err;",
  "                        console.warn('⚠️ Failed endpoint:', url, err.message);",
  "                    }",
  "                }",
  "                throw lastError || new Error('Network info unavailable');",
  "            } catch (err) {",
  "                if (timedOut) {",
  "                    return;",
  "                }",
  "                console.error('❌ Network info failed:', err.message);",
  "                console.error('❌ Error details:', err);",
  "                if (err.message.includes('fetch') || err.message.includes('Failed to fetch') || err.message.includes('NetworkError')) {",
  "                    infoDiv.innerHTML = '<span style=color:#ef4444>🌐 Network Error: Akses melalui URL server yang benar</span>';",
  "                    console.log('💡 Pastikan mengakses dashboard melalui server yang sama (port 5052 jika perlu)');",
  "                } else if (err.message.includes('CORS')) {",
  "                    infoDiv.innerHTML = '<span style=color:#ef4444>🚫 CORS Error: Gunakan URL server</span>';",
  "                } else {",
  "                    infoDiv.innerHTML = '<span style=color:#ef4444>❌ Gagal memuat info jaringan</span>';",
  "                }",
  "            } finally {",
  "                clearTimeout(hardTimeoutId);",
  "                if (!timedOut) {",
  "                    networkFetchInFlight = false;",
  "                }",
  "            }",
  "        }",
  "        // Render system cards"
].join('\n');

content = content.replace(/async function fetchNetworkInfo\(\) \{[\s\S]*?\}\s*\/\/ Render system cards/, newFunction);
fs.writeFileSync(path, content, 'utf8');
